version: "0.5"

environment:
  - "PYTHONUNBUFFERED=1"

processes:
  postgres-init:
    command: |
      mkdir -p "$PGHOST"

      if [ ! -d "$PGDATA" ]; then
        echo "Initializing PostgreSQL database..."
        initdb --auth=trust --no-locale --encoding=UTF8
      fi
    availability:
      restart: no

  postgres:
    command: postgres -k "$PGHOST" -h ""
    depends_on:
      postgres-init:
        condition: process_completed_successfully
    readiness_probe:
      exec:
        command: pg_isready -h "$PGHOST"
      initial_delay_seconds: 1
      period_seconds: 2
    shutdown:
      signal: 2
      timeout_seconds: 10

  postgres-setup:
    command: |
      # Wait for postgres to be ready
      while ! pg_isready -h "$PGHOST" -q; do
        sleep 0.2
      done

      # Create database and user if they don't exist
      psql -h "$PGHOST" -d postgres -tc "SELECT 1 FROM pg_database WHERE datname = '$POSTGRES_DB'" | grep -q 1 || \
        psql -h "$PGHOST" -d postgres -c "CREATE DATABASE $POSTGRES_DB"

      psql -h "$PGHOST" -d postgres -tc "SELECT 1 FROM pg_roles WHERE rolname = '$POSTGRES_USER'" | grep -q 1 || \
        psql -h "$PGHOST" -d postgres -c "CREATE USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD'"

      psql -h "$PGHOST" -d postgres -c "GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER"
      psql -h "$PGHOST" -d "$POSTGRES_DB" -c "GRANT ALL ON SCHEMA public TO $POSTGRES_USER"

      echo "PostgreSQL database '$POSTGRES_DB' ready"
    depends_on:
      postgres:
        condition: process_healthy
    availability:
      restart: no

  backend:
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: backend
    environment:
      - "PYTHONUNBUFFERED=1"
      - "PYTHONDONTWRITEBYTECODE=1"
    depends_on:
      postgres-setup:
        condition: process_completed_successfully
    readiness_probe:
      http_get:
        host: 127.0.0.1
        port: 8000
        path: /core/health/
      initial_delay_seconds: 2
      period_seconds: 5

  frontend:
    command: bun run dev --host
    working_dir: web
